### ISSUE TITLE
Fails to resolve program name if launch name lacks extension

### ISSUE THREAD

**Issue by kolakode** [bitranox/lib_programname#8]
* **I'm submitting a ... **
  - [X] bug report
  - [ ] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Reporting a bug.

* **What is the current behavior?**
lib_programname fails to resolve the program name correctly when the program or a symbolic link pointing to the program has no extension.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
```
$ # the test script
$ cat test.py
#!/usr/bin/env python3
import lib_programname
# this returns the fully resolved path to the launched python program
path_to_program = lib_programname.get_path_executed_script()  # type: pathlib.Path
print(path_to_program)

$ # running the script directly works
$ ./test.py
/Users/tester/test.py

$ # running the script with a .py named symlink works
$ ln -s test.py link2test.py
$ ./link2test.py
/Users/tester/test.py
$ rm link2test.py

$ # running the script with a symlink without an extension fails
$ ln -s test.py link2test
$ ./link2test
/usr/local/lib/python3.9/site-packages/lib_programname/lib_programname.py

$ # running the script directly also fails if it has no extension
$ mv test.py testme
$ ./testme
/usr/local/lib/python3.9/site-packages/lib_programname/lib_programname.py

$ # running the extension-less script with a .py named symlink works!
$ ln -s testme link2test.py
$ ./link2test.py
/Users/tester/testme
```

* **What is the expected behavior?**
./link2test should have reported the same as ./link2test.py: /Users/tester/test.py

* **What is the motivation / use case for changing the behavior?**
N/A

* **Please tell us about your environment:**

- Release Number of the Repository used :  latest
- Python Version : 3.9.4 via brew install python3
- OS, OS Version : macOS Mojave

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)
The minimal demo above indicates the program/script name is correctly resolved if the script or the link to the script has a .py extension, but fails if the script or link being executed has no extension. The last case is interesting, as the link has an extension, but the script does not, yet lib_programname resolves the script name correctly, which confirms this issue only occurs if the launch name (script or symlink executed) has no extension.

**Comment by bitranox** [comment]
will look into it - will take some time, very busy ATM.
If there are no downsides, I will implement it.
yours sincerely
bitranox

**Comment by cazador481** [comment]
Have you had a chance to look into this?

**Comment by bitranox** [comment]
I will look into it soon, please be patient.
yours sincerely
bitranox

**Comment by bitranox** [comment]
Dear @cazador481 , it works now also without extensions.
Please note that on symlinks it always returns the actual script where the link points to, not the symlink itself.
I hope it is helpful for You, please let me know.
yours sincerely
bitranox
